# Generated by Django 6.0 on 2025-12-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.PositiveIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="cinema_movi_title_98764b_idx")
                ],
            },
        ),
    ]
